; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
extra_configs = platformio_override.ini

[secrets]
wifi_flags =
    -D WIFI_SSID='"NOT_SET"'
    -D WIFI_PASS='"NOT_SET"'

[base]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7.4.3
    https://github.com/Seeed-Studio/Seeed_Arduino_SSCMA

build_flags =
    ; Override [secrets] in platformio_override.ini
    ${secrets.wifi_flags}
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3

[app_data_collection]
build_flags =
    ${base.build_flags}
    -D APP_DATA_COLLECTION

[app_inference]
build_flags =
    ${base.build_flags}
    -D APP_INFERENCE

[env:xiao_esp32s3_data_collection]
board = seeed_xiao_esp32s3
extends = 
    base
    app_data_collection